
export const GET_ALL_MOVIE_SUCCESS = 'GET_ALL_MOVIE_SUCCESS';
export const GET_ALL_MOVIE_ERROR = 'GET_ALL_MOVIE_ERROR';


export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_ERROR = 'GET_MOVIE_ERROR';

